services:
  db-ural:
    image: 'postgres:16.3-alpine'
    container_name: 'db-ural'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ural
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 10900:5432

  minio:
    image: 'minio/minio:latest'
    container_name: minio
    environment:
      - MINIO_ROOT_USER=ural
      - MINIO_ROOT_PASSWORD=uralpass
    command: server ~/data --console-address :9090
    ports:
      - 9090:9090
      - 9000:9000

  cars:
    image: kerzhakovn/ural-cars-service
    platform: linux/amd64
    environment:
      SERVER_PORT: 10904
      DB_URL: jdbc:postgresql://db-ural:5432
      DB_NAME: ural
      DB_USER: postgres
      DB_PASS: postgres
      SHOW_SQL: false
      LOGGING_LEVEL_ROOT: INFO
    ports:
      - 10904:10904

volumes:
  pgdata:
  keycloak_data:
